INSERT INTO roles(name) VALUES('ROLE_USER') ON CONFLICT DO NOTHING;

INSERT INTO months(month_number) VALUES(0) ON CONFLICT DO NOTHING;
INSERT INTO months(month_number) VALUES(1) ON CONFLICT DO NOTHING;
INSERT INTO months(month_number) VALUES(2) ON CONFLICT DO NOTHING;
INSERT INTO months(month_number) VALUES(3) ON CONFLICT DO NOTHING;
INSERT INTO months(month_number) VALUES(4) ON CONFLICT DO NOTHING;
INSERT INTO months(month_number) VALUES(5) ON CONFLICT DO NOTHING;
INSERT INTO months(month_number) VALUES(6) ON CONFLICT DO NOTHING;
INSERT INTO months(month_number) VALUES(7) ON CONFLICT DO NOTHING;
INSERT INTO months(month_number) VALUES(8) ON CONFLICT DO NOTHING;
INSERT INTO months(month_number) VALUES(9) ON CONFLICT DO NOTHING;
INSERT INTO months(month_number) VALUES(10) ON CONFLICT DO NOTHING;
INSERT INTO months(month_number) VALUES(11) ON CONFLICT DO NOTHING;
