ALTER TABLE EXPENSE
DROP CONSTRAINT EXPENSE_TYPE_YEAR_FK;

ALTER TABLE EXPENSE
ADD CONSTRAINT EXPENSE_TYPE_YEAR_FK FOREIGN KEY(IDT_EXPENSE_TYPE) REFERENCES EXPENSE_TYPE(IDT_EXPENSE_TYPE) ON DELETE CASCADE;