CREATE SEQUENCE SQ_CUSTOMER_IDT
    INCREMENT 1
    MINVALUE 1
    START 1
    CACHE 1;

CREATE TABLE CUSTOMER (
	IDT_CUSTOMER    BIGINT          NOT NULL,
	NAM_USERNAME    VARCHAR(255)    NOT NULL UNIQUE,
	NAM_EMAIL       VARCHAR(255)    NOT NULL UNIQUE,
	DES_PASSWORD    VARCHAR(255)    NOT NULL,
	CONSTRAINT CUSTOMER_PK PRIMARY KEY (IDT_CUSTOMER)
);