CREATE SEQUENCE SQ_INITIAL_MONEY_IDT
    INCREMENT 1
    MINVALUE 1
    START 1
    CACHE 1;

CREATE TABLE INITIAL_MONEY (
	IDT_INITIAL_MONEY   BIGINT NOT NULL,
    IDT_CUSTOMER        BIGINT NOT NULL,
    IDT_YEAR            BIGINT NOT NULL,
    NUM_INITIAL_MONEY   REAL NOT NULL,
	COD_MONTH           VARCHAR(255),
	CONSTRAINT IDT_INITIAL_MONEY_PK PRIMARY KEY (IDT_INITIAL_MONEY),
	CONSTRAINT INITIAL_MONEY_CUSTOMER_FK FOREIGN KEY(IDT_CUSTOMER) REFERENCES CUSTOMER(IDT_CUSTOMER),
	CONSTRAINT INITIAL_MONEY_YEAR_FK FOREIGN KEY(IDT_YEAR) REFERENCES YEAR(IDT_YEAR),
	UNIQUE (IDT_CUSTOMER, IDT_YEAR, COD_MONTH)
);