CREATE SEQUENCE SQ_EXPENSE_IDT
    INCREMENT 1
    MINVALUE 1
    START 1
    CACHE 1;

CREATE TABLE EXPENSE (
	IDT_EXPENSE         BIGINT NOT NULL,
    IDT_CUSTOMER        BIGINT NOT NULL,
    IDT_YEAR            BIGINT NOT NULL,
    IDT_EXPENSE_TYPE    BIGINT NOT NULL,
	COD_MONTH           VARCHAR(255),
	NAM_EXPENSE         VARCHAR(255),
	NUM_PRICE           REAL,
	FLG_PAID            BOOLEAN,
	CONSTRAINT IDT_EXPENSE_PK PRIMARY KEY (IDT_EXPENSE),
	CONSTRAINT EXPENSE_CUSTOMER_FK FOREIGN KEY(IDT_CUSTOMER) REFERENCES CUSTOMER(IDT_CUSTOMER),
	CONSTRAINT EXPENSE_YEAR_FK FOREIGN KEY(IDT_YEAR) REFERENCES YEAR(IDT_YEAR),
	CONSTRAINT EXPENSE_TYPE_YEAR_FK FOREIGN KEY(IDT_EXPENSE_TYPE) REFERENCES EXPENSE_TYPE(IDT_EXPENSE_TYPE)
);