CREATE SEQUENCE SQ_YEAR_IDT
    INCREMENT 1
    MINVALUE 1
    START 1
    CACHE 1;

CREATE TABLE YEAR (
	IDT_YEAR        BIGINT  NOT NULL,
    IDT_CUSTOMER    BIGINT,
	NUM_YEAR        INTEGER NOT NULL,
	CONSTRAINT YEAR_PK PRIMARY KEY (IDT_YEAR),
	CONSTRAINT YEAR_CUSTOMER_FK FOREIGN KEY(IDT_CUSTOMER) REFERENCES CUSTOMER(IDT_CUSTOMER),
	UNIQUE (IDT_CUSTOMER, NUM_YEAR)
);